mtb-technology/jdb-website

app/besloten-vennootschap/page.tsx
app/en/page.tsx
app/layout.tsx
components/Header.tsx
components/SidebarLayout.tsx
globals.css
middleware.ts
next.config.ts
page.tsx
tailwind.config.js

**Title:** Add Navigation Links, Tailwind, and Middleware
**Description:**
This pull request introduces several updates and improvements to the project:
- **Fix View Path:** Corrected the path in the view to ensure proper rendering and accessibility.
- **Uncommitted Changes:** Additional modifications that enhance the navigation experience and incorporate Tailwind CSS for improved styling and responsiveness.
These changes aim to streamline navigation across the application while leveraging Tailwind for a more modern and cohesive UI. Please review the changes and provide any feedback. Thank you!

add-nav-links-tailwind-middleware

---

app/[local]/page.tsx
app/besloten-vennootschap/page.tsx
app/i18n/translations.json
app/layout.tsx
app/page.tsx
components/Header.tsx
components/SidebarLayout.tsx
middleware.ts
next.config.ts

Enhance middleware to improve locale prefix handling. The code now  allows English routes to pass through without redirection, and  redirects Dutch routes to paths without prefixes. The logic for  adding the English locale prefix is streamlined. Additionally,  simplify the sidebar navigation rendering by using a helper  function to maintain consistency and reduce duplication.  Remove unused Home component in the English page for  cleaner codebase.

refactor: update middleware for locale handling

---

app/besloten-vennootschap/page.tsx

Replace apostrophes and quotes with proper HTML entities in the text 
content of the HeroSection and BVSupportSection components for 
consistency and to prevent potential rendering issues. This ensures 
the text displays correctly across all browsers.

fix: update HTML entities in BV's text content

---

app/en/how-it-works/page.tsx
app/hoe-werkt-het/page.tsx
dictionaries/en.json
dictionaries/nl.json
lib/routes.ts

Implement the "How It Works" page to guide users on the functionality 
of the application. Include the main components: Header, StepsSection, 
and Footer. Add dynamic content based on locale for better user 
experience. Extend the English dictionary with relevant section 
translations, enhancing accessibility and clarity of service 
instructions for users.

feat: add "How It Works" page and translations

---

app/blog/page.tsx
app/disclaimer/page.tsx
app/en/about-us/page.tsx
app/en/blog/page.tsx
app/en/disclaimer/page.tsx
app/en/find-advisor/page.tsx
app/en/how-it-works/page.tsx
app/en/page.tsx
app/en/privacy/page.tsx
app/en/topics/[topic]/page.tsx
app/onderwerpen/[topic]/page.tsx
app/privacy/page.tsx
components/sections/FAQAndBlogSection.tsx
dictionaries/en.json
lib/routes.ts

Refactor the FAQ and Blog section to enhance props handling by
providing more granular control over title and items. Implement
localization for various pages, ensuring each page generates
metadata based on the locale. Remove redundant footer translations
and adjust component imports accordingly to streamline the codebase.

feat: update FAQ and blog section, add localization support

---

app/blog/[post]/page.tsx
app/components/back-button.tsx
components/back-button.d.ts
components/back-button.tsx
lib/api/JDBApi.ts

Adds a new blog post page that fetches and displays individual post 
content, including the title, author, publish date, and featured 
image. Implements navigation

feat(blog): create detailed blog post page with content

---

app/components/providers/tracking-provider.tsx
app/layout.tsx
app/lib/tracking-server.ts
app/lib/tracking.ts
app/page.tsx
components/chat/ChatWindow.tsx
package-lock.json
package.json

Removes unnecessary peer dependencies from various packages in the 
package-lock.json file. Updates ESLint and related packages to their 
latest versions for improved linting capabilities and compatibility 
with the current project setup.

refactor(package-lock): remove peer dependencies from devDeps

---

next.config.ts

Removes unnecessary `key` fields from the redirection rules  in `next.config.ts` to streamline the configuration. This  change enhances readability and maintains functionality by  keeping only the essential

refactor: simplify host redirection rules in next.config.ts

---

app/chat/dictionaries.json
app/chat/dictionary.ts
app/en/chat/[employee]/page.tsx
components/chat/ChatInterface.tsx
components/chat/ChatWindow.tsx
dictionaries/en.json
dictionaries/nl.json
lib/chat-stream.ts
lib/routes.ts
next.config.ts

Remove unnecessary styling from the chat interface, simplifying the  component's layout. Update the translation keys and routes to reflect  new blog category structures and ensure accurate navigation.  Consolidate chat routing for better clarity and efficiency in  linking to relevant resources.

refactor: update chat display and restructure routes

---

dictionaries/en.json
lib/routes.ts

fixed topics and chats in routing

fixed topics and chats in routing

---

app/[...not_found]/page.tsx
app/not-found.tsx
app/onderwerpen/[topic]/page.tsx
components/chat/ChatWindow.tsx

Add URLs to images in the ChatWindow component for better 
resource linking. Update locale from "nl" to "en" in the 
generateStaticParams function to support English routes. 
Introduce a new NotFound page with a custom 404 message 
and a link to return to the homepage for improved user 
experience and navigation.

feat: enhance chat window and add 404 page

---

app/blog/page.tsx
components/SidebarLayout.tsx

Adjust the navigation in SidebarLayout to handle overflow 
with added classes for scrolling. Remove unnecessary console 
log from InitialBlogData for cleaner code output.

style: improve sidebar overflow and formatting

---

app/chat/dictionaries.json
components/chat/ChatInterface.tsx
components/chat/ChatWindow.tsx
components/ui/select.tsx
package.json
pnpm-lock.yaml

Adds employee selection capability to the chat interface. Introduces 
dynamic loading of assistant names and descriptions based on the 
current language and employee ID from the URL. Refines the 
dictionary data to include "assistantName" and "assistantDescription"

feat(chat): enhance chat functionality with employee selection

---

app/chat/dictionary.ts
components/Footer.tsx
components/LanguageSwitcher.tsx
components/chat/ChatInterface.tsx
dictionaries/en.json
dictionaries/nl.json
lib/routes.ts

Refactor the `getLocalizedPath` function to determine the source 
locale based on path content rather than directly from the provided 
locale. This improves handling of dynamic segments. Update chat 
mappings for reverse lookups and optimize segment translations. 
Add additional metadata to the Dutch localization JSON and define 
a new interface for chat employees. This ensures better data 
structure and maintainability.

feat(routes): enhance localization logic for paths

---

app/globals.css
components/chat/ChatInterface.tsx
package.json
pnpm-lock.yaml

Integrate the Tailwind CSS typography plugin for better text styling. 
Enhance the `ChatInterface` component by introducing a tool call 
metadata interface and logging relevant data for improved debugging. 
Update dependencies in package configurations for compatibility 
and better functionality.

feat: add tailwind typography plugin and improve chat logs

---

components/chat/ChatInterface.tsx
lib/chat-stream.ts
lib/routes.ts

Update the fallback for the current employee ID to "not-found" instead of 
"algemene-vragen" to better reflect an invalid state. Remove unused console 
logs to clean up the code. Import tracking data and integrate it into the 
tool call tracking for enhanced analytics. Revise the localized path to ensure 
the English locale prefix is consistently applied.

fix(chat): update handling of employee ID and improve tracking

---

app/disclaimer/page.tsx
app/en/privacy/page.tsx
app/privacy/page.tsx
components/sections/FAQAndBlogSection.tsx
components/ui/accordion.tsx
next.config.ts

Restructure the layout of the disclaimer and privacy policy pages by   introducing a wrapper div. Enhance the styling by adding padding to   improve readability. These changes improve user experience and   visual consistency across sections.

refactor: Update disclaimer and privacy pages layout

---

app/layout.tsx
app/onderwerpen/[topic]/page.tsx
components/AdsPage.tsx
components/DynamicForm.tsx
components/Header.tsx
components/chat/ChatInterface.tsx
components/chat/ChatWindow.tsx
components/sections/SupportSection.tsx
components/ui/sheet.tsx

Rearrange import statements in `sheet.tsx` for consistency.  Add `generateZodSchema` and `getConditionFields` to dependency  array in `useEffect` of `

refactor: tidy up imports and improve accessibility

---

components/Header.tsx
components/LanguageSwitcher.tsx
components/chat/ChatInterface.tsx
components/chat/ChatWindow.tsx

Refactor the ChatWindow component to update the top padding 
from 85px to 83px for better alignment. Improve the formatting 
of imports and JSX in the LanguageSwitcher component for 
enhanced readability. Enhance the Header

fix: adjust layout and improve code formatting

---

next.config.ts

Implement new redirects to external application URLs for admin, login,   register, and saas paths. These changes maintain the existing routes for   users while directing them to the appropriate external destinations.   This improves navigation and user experience for the application.

feat(redirects): add new redirects for external paths

---

components/DynamicForm.tsx

Adds support for file inputs and checkboxes in the DynamicForm component. 
Introduces `accept` property for file fields to specify accepted file types. 
Checkboxes enable multiple

feat: add file input and checkbox support to DynamicForm

---

app/en/(ads)/incometax-return/page.tsx
app/en/(ads)/m-form/page.tsx
app/en/(ads)/tax-advisor/page.tsx
app/over-ons/page.tsx
components/Header.tsx
components/chat/ChatWindow.tsx
dictionaries/en.json
dictionaries/nl.json
next.config.ts

Improvements & feedback verwerkt:
- Forms van en pages
- GDPR content op alle pages
- over ons button links dynamic for language
- aantal reviews aangepast / weggehaald
- stel je vraag in chat box dynamic for language
- blog category leeg op pages om alle recente te tonen voor nu

Branch bo smallfixes

---

lib/chat-stream.ts

Add tracking ID and lead source as optional parameters to the 
sendMessage function. These headers are included in the API request 
to improve analytics and tracking of user interactions.

feat(chat-stream): add tracking ID and lead source headers

---

components/chat/ChatInterface.tsx
lib/chat-stream.ts

feat(chat): allow null values for tracking fields

---

app/sitemap.ts

refactor: streamline sitemap generation process

---

app/(pages)/over-ons/page.tsx

Modify grid classes in the About Us page to enhance  responsiveness. Change `md` to `lg` for certain sections  to better

style: update grid classes for better responsiveness

---

app/blog/components/BlogContentClient.tsx
app/blog/components/NewsletterSubscription.tsx
lib/api/JDBApi.ts

Introduce a newsletter subscription component to enhance user 
engagement. The new `NewsletterSubscription` component is created to 
handle user email input, manage subscription state, and interact 
with the API for email subscriptions. The existing newsletter section 
is replaced with this new

feat: add newsletter subscription component

---

app/components/providers/tracking-provider.tsx
app/lib/tracking.ts

Add a new field for Hotjar User ID in the TrackingData interface.  Implement a function to retrieve the Hotjar User ID from cookies  and include it in the tracking data set within the TrackingProvider.  This change enables better user tracking and analytics integration  with Hotjar.

feat(tracking): add Hotjar User ID handling to tracking data

---

app/blog/[post]/page.tsx
app/blog/components/BlogContentClient.tsx
app/en/blog/[post]/page.tsx
components/Header.tsx
components/SidebarLayout.tsx

Update the blog post page to dynamically set locale based on URL  parameters, improving localization support. Add language switcher to the  header for easier navigation. Adjust sidebar and blog content styles for  consistency and improved responsiveness by modifying spacing and  overflow handling. Additionally, implement static generation of blog  posts for English locale to enhance performance and SEO.

feat: enhance blog post and layout components

---

app/blog/[post]/page.tsx
app/components/BlogPostContent.tsx
app/en/blog/[post]/page.tsx
lib/api/JDBApi.ts

Refactor the BlogPostPage component to improve the layout by introducing a new main structure, including a header and footer. Update the BlogPostContent component to display blog details.  Replace the existing HTML content parsing logic and streamline data retrieval with improved parameter handling.

feat: enhance blog post page layout and functionality

---

app/components/providers/tracking-provider.tsx

Add console logs to track the existing lead source and 
document referrer values. This provides better visibility 
into lead source determination for debugging purposes.

feat(tracking): add logging for lead source and referrer

---

app/components/providers/tracking-provider.tsx
components/DynamicForm.tsx
components/chat/ChatInterface.tsx
components/forms/dynamic-form.tsx
lib/chat-stream.ts

Add properties for gadSource, gclid, and fbclid to the tracking  functionality to enhance tracking capabilities. Ensure that these  tracking parameters are parsed from the URL and incorporated into  the tracking data throughout the application, improving data  collection for analytics purposes.

feat(tracking): add support for gadSource, gclid, and fbclid

---

lib/chat-stream.ts

Include new parameters for gadSource, gclid, fbclid, and  hotjarUserId in chat message headers. This enhances tracking  capabilities and improves the ability to analyze user  interactions. Reorder app_locale to app-locale for consistency.

feat: add additional tracking parameters to message headers

---

components/chat/ChatInterface.tsx

Includes additional tracking parameters such as utm_params,  hotjar_user_id, gad_source, gclid, and fbclid to enhance  data collection for analytics. This improves our ability to  track user behavior and source attribution effectively.

feat(chat): add tracking parameters to ChatInterface

---

components/DynamicForm.tsx
components/chat/ChatInterface.tsx

Removes the console log statement for message_id in ChatInterface to  clean up the code. Adds additional tracking data fields (gad_source,  gclid, and fbclid) in DynamicForm for improved data capture and  analytics. This enhances the tracking capabilities of user interactions.

refactor: remove console log in ChatInterface and add tracking data

---

components/forms/dynamic-form.tsx

Introduce gad_source, gclid, and fbclid to DynamicForm for enhanced 
tracking capabilities. These changes enable better analysis of user 
acquisition sources and improve campaign performance evaluation.

feat: add additional tracking parameters to DynamicForm
